## h2 ?????? ??
spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://125.138.61.176:5432/postgres
    username: postgres
    password: 1234

  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

logging:
  level:
    me.sanghoon: DEBUG

jwt:
  header: Authorization
  secret: dfklWWHObhUWHEJKHhkjHWKXEHWUIEHXWUIWjhkjHJKWHEJWKeKEhjhKJHEWlhjkjklewkjkljkljewkljqnnjkbctjkwbtek
  token-validity-in-seconds: 86400
